server:
  port: 8080
  servlet:
    context-path: '/'
spring:
  #mysql数据源
  datasource:
    url: jdbc:mysql:///heima_movies?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  #自定义静态文件位置
  resources:
    static-locations: classpath:/templates/
  #thymeleaf 文件位置配置
  thymeleaf:
    # 自定义前缀
    prefix: classpath:/templates/
    # 自定义后缀
    suffix: .html

# mybatis简单配置
mybatis:
  # 指定mapper映射文件
  mapper-locations: classpath:mapper/*
  configuration:
    # 开启驼峰式映射
    map-underscore-to-camel-case: true

# 日志级别设置格式是
# 包名: 日志级别(常用的级别有4个: debug info warn error)
logging:
  level:
    com.lofxve: info
sms:
  username: 张三
  password: 123
