
spring:
  datasource:
    url: jdbc:mysql:///heima_movies?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  boot:
    admin:
      client:
        url: http://localhost:8080/
#开启logging myabtis语句打印
#logback配置
logging:
  pattern:
    console: '%d -%msg%n'
#  path: D:/data/log/seller.log
  level:
    root: info

mybatis-plus:
  configuration:
    # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081